-- GENERATED by scripts/gen-seed-sql.mjs — do not edit by hand.
-- Regenerate after any change to data/teams.json or data/schedule.json.

begin;

-- Teams. Names only: no emails, no phone numbers.
insert into public.teams (id, name, seed, captain, players, roster_pending, has_net, color_a, color_b, blurb) values (
  'deez-nets', 'Deez Nets', 1, 'Michael Keo', array['Michael Keo', 'Cynthia', 'Claire', 'Nick']::text[],
  0, true, '#2D3561', '#5B6BC0', 'Bringing a net and the pun. Both essential.'
) on conflict (id) do update set
  name = excluded.name, seed = excluded.seed, captain = excluded.captain,
  players = excluded.players, roster_pending = excluded.roster_pending,
  has_net = excluded.has_net, color_a = excluded.color_a,
  color_b = excluded.color_b, blurb = excluded.blurb;
insert into public.teams (id, name, seed, captain, players, roster_pending, has_net, color_a, color_b, blurb) values (
  'haikyuties', 'Haikyuties', 2, 'Janna Remperas', array['Janna Remperas', 'Shan']::text[],
  2, false, '#FF6B35', '#F7931E', 'Fly high. Anime rules apply.'
) on conflict (id) do update set
  name = excluded.name, seed = excluded.seed, captain = excluded.captain,
  players = excluded.players, roster_pending = excluded.roster_pending,
  has_net = excluded.has_net, color_a = excluded.color_a,
  color_b = excluded.color_b, blurb = excluded.blurb;
insert into public.teams (id, name, seed, captain, players, roster_pending, has_net, color_a, color_b, blurb) values (
  'tequila-mockingbird', 'Tequila Mockingbird', 3, 'Grant McLean', array['Grant McLean', 'Neil McLean', 'Shannon O''Donoghue', 'Peter Kress']::text[],
  0, true, '#B4D33A', '#E8B33D', 'Best team name in the field and they know it.'
) on conflict (id) do update set
  name = excluded.name, seed = excluded.seed, captain = excluded.captain,
  players = excluded.players, roster_pending = excluded.roster_pending,
  has_net = excluded.has_net, color_a = excluded.color_a,
  color_b = excluded.color_b, blurb = excluded.blurb;
insert into public.teams (id, name, seed, captain, players, roster_pending, has_net, color_a, color_b, blurb) values (
  'cinnamon-rolls', 'Cinnamon Rolls', 4, 'Neal Matta', array['Neal Matta', 'Will', 'Alanah', 'Amy']::text[],
  0, false, '#D98E5F', '#A0522D', 'Your host''s team. Sweet, warm, rolls a lot.'
) on conflict (id) do update set
  name = excluded.name, seed = excluded.seed, captain = excluded.captain,
  players = excluded.players, roster_pending = excluded.roster_pending,
  has_net = excluded.has_net, color_a = excluded.color_a,
  color_b = excluded.color_b, blurb = excluded.blurb;
insert into public.teams (id, name, seed, captain, players, roster_pending, has_net, color_a, color_b, blurb) values (
  'perros-calientes', 'Perros Calientes', 5, 'Alfonso', array['Alfonso', 'Hina', 'Asher', 'Medhi']::text[],
  0, false, '#E63946', '#F4A261', 'Hot dogs. Served on grass.'
) on conflict (id) do update set
  name = excluded.name, seed = excluded.seed, captain = excluded.captain,
  players = excluded.players, roster_pending = excluded.roster_pending,
  has_net = excluded.has_net, color_a = excluded.color_a,
  color_b = excluded.color_b, blurb = excluded.blurb;
insert into public.teams (id, name, seed, captain, players, roster_pending, has_net, color_a, color_b, blurb) values (
  'bumping-buds', 'Bumping Buds', 6, 'Jamie Kolar', array['Jamie Kolar', 'Kim', 'Elvis', 'Diego']::text[],
  0, false, '#E056A0', '#9B59B6', 'Here for the bump and the buds.'
) on conflict (id) do update set
  name = excluded.name, seed = excluded.seed, captain = excluded.captain,
  players = excluded.players, roster_pending = excluded.roster_pending,
  has_net = excluded.has_net, color_a = excluded.color_a,
  color_b = excluded.color_b, blurb = excluded.blurb;

-- Games. Scores stay null until a captain submits them.
insert into public.games (id, slot, phase, court, start_time, label, team_a, team_b, ref_team, a_seed, b_seed, a_winner_of, b_winner_of, a_loser_of, b_loser_of) values (
  'p1', 1, 'pool', 1, '10:00', null,
  'deez-nets', 'bumping-buds', 'tequila-mockingbird',
  null, null,
  null, null,
  null, null
) on conflict (id) do update set
  slot = excluded.slot, phase = excluded.phase, court = excluded.court,
  start_time = excluded.start_time, label = excluded.label,
  team_a = excluded.team_a, team_b = excluded.team_b, ref_team = excluded.ref_team,
  a_seed = excluded.a_seed, b_seed = excluded.b_seed,
  a_winner_of = excluded.a_winner_of, b_winner_of = excluded.b_winner_of,
  a_loser_of = excluded.a_loser_of, b_loser_of = excluded.b_loser_of;
insert into public.games (id, slot, phase, court, start_time, label, team_a, team_b, ref_team, a_seed, b_seed, a_winner_of, b_winner_of, a_loser_of, b_loser_of) values (
  'p2', 1, 'pool', 2, '10:00', null,
  'haikyuties', 'perros-calientes', 'cinnamon-rolls',
  null, null,
  null, null,
  null, null
) on conflict (id) do update set
  slot = excluded.slot, phase = excluded.phase, court = excluded.court,
  start_time = excluded.start_time, label = excluded.label,
  team_a = excluded.team_a, team_b = excluded.team_b, ref_team = excluded.ref_team,
  a_seed = excluded.a_seed, b_seed = excluded.b_seed,
  a_winner_of = excluded.a_winner_of, b_winner_of = excluded.b_winner_of,
  a_loser_of = excluded.a_loser_of, b_loser_of = excluded.b_loser_of;
insert into public.games (id, slot, phase, court, start_time, label, team_a, team_b, ref_team, a_seed, b_seed, a_winner_of, b_winner_of, a_loser_of, b_loser_of) values (
  'p3', 2, 'pool', 1, '10:25', null,
  'bumping-buds', 'cinnamon-rolls', 'deez-nets',
  null, null,
  null, null,
  null, null
) on conflict (id) do update set
  slot = excluded.slot, phase = excluded.phase, court = excluded.court,
  start_time = excluded.start_time, label = excluded.label,
  team_a = excluded.team_a, team_b = excluded.team_b, ref_team = excluded.ref_team,
  a_seed = excluded.a_seed, b_seed = excluded.b_seed,
  a_winner_of = excluded.a_winner_of, b_winner_of = excluded.b_winner_of,
  a_loser_of = excluded.a_loser_of, b_loser_of = excluded.b_loser_of;
insert into public.games (id, slot, phase, court, start_time, label, team_a, team_b, ref_team, a_seed, b_seed, a_winner_of, b_winner_of, a_loser_of, b_loser_of) values (
  'p4', 2, 'pool', 2, '10:25', null,
  'haikyuties', 'tequila-mockingbird', 'perros-calientes',
  null, null,
  null, null,
  null, null
) on conflict (id) do update set
  slot = excluded.slot, phase = excluded.phase, court = excluded.court,
  start_time = excluded.start_time, label = excluded.label,
  team_a = excluded.team_a, team_b = excluded.team_b, ref_team = excluded.ref_team,
  a_seed = excluded.a_seed, b_seed = excluded.b_seed,
  a_winner_of = excluded.a_winner_of, b_winner_of = excluded.b_winner_of,
  a_loser_of = excluded.a_loser_of, b_loser_of = excluded.b_loser_of;
insert into public.games (id, slot, phase, court, start_time, label, team_a, team_b, ref_team, a_seed, b_seed, a_winner_of, b_winner_of, a_loser_of, b_loser_of) values (
  'p5', 3, 'pool', 1, '10:50', null,
  'tequila-mockingbird', 'cinnamon-rolls', 'haikyuties',
  null, null,
  null, null,
  null, null
) on conflict (id) do update set
  slot = excluded.slot, phase = excluded.phase, court = excluded.court,
  start_time = excluded.start_time, label = excluded.label,
  team_a = excluded.team_a, team_b = excluded.team_b, ref_team = excluded.ref_team,
  a_seed = excluded.a_seed, b_seed = excluded.b_seed,
  a_winner_of = excluded.a_winner_of, b_winner_of = excluded.b_winner_of,
  a_loser_of = excluded.a_loser_of, b_loser_of = excluded.b_loser_of;
insert into public.games (id, slot, phase, court, start_time, label, team_a, team_b, ref_team, a_seed, b_seed, a_winner_of, b_winner_of, a_loser_of, b_loser_of) values (
  'p6', 3, 'pool', 2, '10:50', null,
  'deez-nets', 'perros-calientes', 'bumping-buds',
  null, null,
  null, null,
  null, null
) on conflict (id) do update set
  slot = excluded.slot, phase = excluded.phase, court = excluded.court,
  start_time = excluded.start_time, label = excluded.label,
  team_a = excluded.team_a, team_b = excluded.team_b, ref_team = excluded.ref_team,
  a_seed = excluded.a_seed, b_seed = excluded.b_seed,
  a_winner_of = excluded.a_winner_of, b_winner_of = excluded.b_winner_of,
  a_loser_of = excluded.a_loser_of, b_loser_of = excluded.b_loser_of;
insert into public.games (id, slot, phase, court, start_time, label, team_a, team_b, ref_team, a_seed, b_seed, a_winner_of, b_winner_of, a_loser_of, b_loser_of) values (
  'p7', 4, 'pool', 1, '11:15', null,
  'bumping-buds', 'haikyuties', 'cinnamon-rolls',
  null, null,
  null, null,
  null, null
) on conflict (id) do update set
  slot = excluded.slot, phase = excluded.phase, court = excluded.court,
  start_time = excluded.start_time, label = excluded.label,
  team_a = excluded.team_a, team_b = excluded.team_b, ref_team = excluded.ref_team,
  a_seed = excluded.a_seed, b_seed = excluded.b_seed,
  a_winner_of = excluded.a_winner_of, b_winner_of = excluded.b_winner_of,
  a_loser_of = excluded.a_loser_of, b_loser_of = excluded.b_loser_of;
insert into public.games (id, slot, phase, court, start_time, label, team_a, team_b, ref_team, a_seed, b_seed, a_winner_of, b_winner_of, a_loser_of, b_loser_of) values (
  'p8', 4, 'pool', 2, '11:15', null,
  'deez-nets', 'tequila-mockingbird', 'perros-calientes',
  null, null,
  null, null,
  null, null
) on conflict (id) do update set
  slot = excluded.slot, phase = excluded.phase, court = excluded.court,
  start_time = excluded.start_time, label = excluded.label,
  team_a = excluded.team_a, team_b = excluded.team_b, ref_team = excluded.ref_team,
  a_seed = excluded.a_seed, b_seed = excluded.b_seed,
  a_winner_of = excluded.a_winner_of, b_winner_of = excluded.b_winner_of,
  a_loser_of = excluded.a_loser_of, b_loser_of = excluded.b_loser_of;
insert into public.games (id, slot, phase, court, start_time, label, team_a, team_b, ref_team, a_seed, b_seed, a_winner_of, b_winner_of, a_loser_of, b_loser_of) values (
  'p9', 5, 'pool', 1, '11:40', null,
  'cinnamon-rolls', 'haikyuties', 'deez-nets',
  null, null,
  null, null,
  null, null
) on conflict (id) do update set
  slot = excluded.slot, phase = excluded.phase, court = excluded.court,
  start_time = excluded.start_time, label = excluded.label,
  team_a = excluded.team_a, team_b = excluded.team_b, ref_team = excluded.ref_team,
  a_seed = excluded.a_seed, b_seed = excluded.b_seed,
  a_winner_of = excluded.a_winner_of, b_winner_of = excluded.b_winner_of,
  a_loser_of = excluded.a_loser_of, b_loser_of = excluded.b_loser_of;
insert into public.games (id, slot, phase, court, start_time, label, team_a, team_b, ref_team, a_seed, b_seed, a_winner_of, b_winner_of, a_loser_of, b_loser_of) values (
  'p10', 5, 'pool', 2, '11:40', null,
  'perros-calientes', 'bumping-buds', 'tequila-mockingbird',
  null, null,
  null, null,
  null, null
) on conflict (id) do update set
  slot = excluded.slot, phase = excluded.phase, court = excluded.court,
  start_time = excluded.start_time, label = excluded.label,
  team_a = excluded.team_a, team_b = excluded.team_b, ref_team = excluded.ref_team,
  a_seed = excluded.a_seed, b_seed = excluded.b_seed,
  a_winner_of = excluded.a_winner_of, b_winner_of = excluded.b_winner_of,
  a_loser_of = excluded.a_loser_of, b_loser_of = excluded.b_loser_of;
insert into public.games (id, slot, phase, court, start_time, label, team_a, team_b, ref_team, a_seed, b_seed, a_winner_of, b_winner_of, a_loser_of, b_loser_of) values (
  'p11', 6, 'pool', 1, '12:05', null,
  'deez-nets', 'cinnamon-rolls', 'haikyuties',
  null, null,
  null, null,
  null, null
) on conflict (id) do update set
  slot = excluded.slot, phase = excluded.phase, court = excluded.court,
  start_time = excluded.start_time, label = excluded.label,
  team_a = excluded.team_a, team_b = excluded.team_b, ref_team = excluded.ref_team,
  a_seed = excluded.a_seed, b_seed = excluded.b_seed,
  a_winner_of = excluded.a_winner_of, b_winner_of = excluded.b_winner_of,
  a_loser_of = excluded.a_loser_of, b_loser_of = excluded.b_loser_of;
insert into public.games (id, slot, phase, court, start_time, label, team_a, team_b, ref_team, a_seed, b_seed, a_winner_of, b_winner_of, a_loser_of, b_loser_of) values (
  'p12', 6, 'pool', 2, '12:05', null,
  'perros-calientes', 'tequila-mockingbird', 'bumping-buds',
  null, null,
  null, null,
  null, null
) on conflict (id) do update set
  slot = excluded.slot, phase = excluded.phase, court = excluded.court,
  start_time = excluded.start_time, label = excluded.label,
  team_a = excluded.team_a, team_b = excluded.team_b, ref_team = excluded.ref_team,
  a_seed = excluded.a_seed, b_seed = excluded.b_seed,
  a_winner_of = excluded.a_winner_of, b_winner_of = excluded.b_winner_of,
  a_loser_of = excluded.a_loser_of, b_loser_of = excluded.b_loser_of;

-- Bracket rows reference semifinal ids, so they must land after the pool rows.
insert into public.games (id, slot, phase, court, start_time, label, team_a, team_b, ref_team, a_seed, b_seed, a_winner_of, b_winner_of, a_loser_of, b_loser_of) values (
  'sf1', 7, 'bracket', 1, '12:40', 'Semifinal 1',
  null, null, null,
  1, 4,
  null, null,
  null, null
) on conflict (id) do update set
  slot = excluded.slot, phase = excluded.phase, court = excluded.court,
  start_time = excluded.start_time, label = excluded.label,
  team_a = excluded.team_a, team_b = excluded.team_b, ref_team = excluded.ref_team,
  a_seed = excluded.a_seed, b_seed = excluded.b_seed,
  a_winner_of = excluded.a_winner_of, b_winner_of = excluded.b_winner_of,
  a_loser_of = excluded.a_loser_of, b_loser_of = excluded.b_loser_of;
insert into public.games (id, slot, phase, court, start_time, label, team_a, team_b, ref_team, a_seed, b_seed, a_winner_of, b_winner_of, a_loser_of, b_loser_of) values (
  'sf2', 7, 'bracket', 2, '12:40', 'Semifinal 2',
  null, null, null,
  2, 3,
  null, null,
  null, null
) on conflict (id) do update set
  slot = excluded.slot, phase = excluded.phase, court = excluded.court,
  start_time = excluded.start_time, label = excluded.label,
  team_a = excluded.team_a, team_b = excluded.team_b, ref_team = excluded.ref_team,
  a_seed = excluded.a_seed, b_seed = excluded.b_seed,
  a_winner_of = excluded.a_winner_of, b_winner_of = excluded.b_winner_of,
  a_loser_of = excluded.a_loser_of, b_loser_of = excluded.b_loser_of;
insert into public.games (id, slot, phase, court, start_time, label, team_a, team_b, ref_team, a_seed, b_seed, a_winner_of, b_winner_of, a_loser_of, b_loser_of) values (
  'final', 8, 'bracket', 1, '1:15', 'Final',
  null, null, null,
  null, null,
  'sf1', 'sf2',
  null, null
) on conflict (id) do update set
  slot = excluded.slot, phase = excluded.phase, court = excluded.court,
  start_time = excluded.start_time, label = excluded.label,
  team_a = excluded.team_a, team_b = excluded.team_b, ref_team = excluded.ref_team,
  a_seed = excluded.a_seed, b_seed = excluded.b_seed,
  a_winner_of = excluded.a_winner_of, b_winner_of = excluded.b_winner_of,
  a_loser_of = excluded.a_loser_of, b_loser_of = excluded.b_loser_of;
insert into public.games (id, slot, phase, court, start_time, label, team_a, team_b, ref_team, a_seed, b_seed, a_winner_of, b_winner_of, a_loser_of, b_loser_of) values (
  'third', 8, 'bracket', 2, '1:15', '3rd Place',
  null, null, null,
  null, null,
  null, null,
  'sf1', 'sf2'
) on conflict (id) do update set
  slot = excluded.slot, phase = excluded.phase, court = excluded.court,
  start_time = excluded.start_time, label = excluded.label,
  team_a = excluded.team_a, team_b = excluded.team_b, ref_team = excluded.ref_team,
  a_seed = excluded.a_seed, b_seed = excluded.b_seed,
  a_winner_of = excluded.a_winner_of, b_winner_of = excluded.b_winner_of,
  a_loser_of = excluded.a_loser_of, b_loser_of = excluded.b_loser_of;

commit;
