-- GENERATED by scripts/gen-seed-sql.mjs — do not edit by hand.
-- Regenerate after any change to data/teams.json or data/schedule.json.

begin;

-- Games and teams that are not part of this tournament.
delete from public.games where id not in ('p1', 'p2', 'p3', 'p4', 'p5', 'p6', 'sf1', 'sf2', 'wf', 'le', 'lf', 'final', 'decider');

-- Teams. Names only: no emails, no phone numbers.
insert into public.teams (id, name, seed, captain, players, roster_pending, has_net, color_a, color_b, blurb) values (
  'deez-nets', 'Deez Nets', 1, 'Michael Keo', array['Michael Keo', 'Miggy', 'Cynthia', 'Nick']::text[],
  0, true, '#2D3561', '#5B6BC0', 'Defending champions. Still bringing a net and the pun.'
) on conflict (id) do update set
  name = excluded.name, seed = excluded.seed, captain = excluded.captain,
  players = excluded.players, roster_pending = excluded.roster_pending,
  has_net = excluded.has_net, color_a = excluded.color_a,
  color_b = excluded.color_b, blurb = excluded.blurb;
insert into public.teams (id, name, seed, captain, players, roster_pending, has_net, color_a, color_b, blurb) values (
  'annies-friends', 'Annie''s Friends', 2, 'Grant McLean', array['Grant McLean', 'Karan', 'Annie', 'Annie''s Friend']::text[],
  0, true, '#7B2D8E', '#E056A0', 'Annie, and people who know Annie.'
) on conflict (id) do update set
  name = excluded.name, seed = excluded.seed, captain = excluded.captain,
  players = excluded.players, roster_pending = excluded.roster_pending,
  has_net = excluded.has_net, color_a = excluded.color_a,
  color_b = excluded.color_b, blurb = excluded.blurb;
insert into public.teams (id, name, seed, captain, players, roster_pending, has_net, color_a, color_b, blurb) values (
  'aaa-roadside-assistance', 'AAA Roadside Assistance', 3, 'Nick Mitchell', array['Nick Mitchell', 'Izzy Grisoli', 'Asher Friedman', 'Alec Brandel']::text[],
  0, false, '#C8102E', '#1F4E9C', 'Here to help. Mostly with digs.'
) on conflict (id) do update set
  name = excluded.name, seed = excluded.seed, captain = excluded.captain,
  players = excluded.players, roster_pending = excluded.roster_pending,
  has_net = excluded.has_net, color_a = excluded.color_a,
  color_b = excluded.color_b, blurb = excluded.blurb;
insert into public.teams (id, name, seed, captain, players, roster_pending, has_net, color_a, color_b, blurb) values (
  'cinnamon-rolls', 'Cinnamon Rolls', 4, 'Neal Matta', array['Neal Matta', 'Alanah', 'Jess', 'Jordyn']::text[],
  0, false, '#D98E5F', '#A0522D', 'Your host''s team. Sweet, warm, rolls a lot.'
) on conflict (id) do update set
  name = excluded.name, seed = excluded.seed, captain = excluded.captain,
  players = excluded.players, roster_pending = excluded.roster_pending,
  has_net = excluded.has_net, color_a = excluded.color_a,
  color_b = excluded.color_b, blurb = excluded.blurb;

-- Games. Scores stay null until a captain submits them.
insert into public.games (id, slot, phase, court, start_time, label, team_a, team_b, a_seed, b_seed, a_winner_of, b_winner_of, a_loser_of, b_loser_of) values (
  'p1', 1, 'pool', 1, '10:00', null,
  'deez-nets', 'cinnamon-rolls',
  null, null,
  null, null,
  null, null
) on conflict (id) do update set
  slot = excluded.slot, phase = excluded.phase, court = excluded.court,
  start_time = excluded.start_time, label = excluded.label,
  team_a = excluded.team_a, team_b = excluded.team_b,
  a_seed = excluded.a_seed, b_seed = excluded.b_seed,
  a_winner_of = excluded.a_winner_of, b_winner_of = excluded.b_winner_of,
  a_loser_of = excluded.a_loser_of, b_loser_of = excluded.b_loser_of;
insert into public.games (id, slot, phase, court, start_time, label, team_a, team_b, a_seed, b_seed, a_winner_of, b_winner_of, a_loser_of, b_loser_of) values (
  'p2', 1, 'pool', 2, '10:00', null,
  'annies-friends', 'aaa-roadside-assistance',
  null, null,
  null, null,
  null, null
) on conflict (id) do update set
  slot = excluded.slot, phase = excluded.phase, court = excluded.court,
  start_time = excluded.start_time, label = excluded.label,
  team_a = excluded.team_a, team_b = excluded.team_b,
  a_seed = excluded.a_seed, b_seed = excluded.b_seed,
  a_winner_of = excluded.a_winner_of, b_winner_of = excluded.b_winner_of,
  a_loser_of = excluded.a_loser_of, b_loser_of = excluded.b_loser_of;
insert into public.games (id, slot, phase, court, start_time, label, team_a, team_b, a_seed, b_seed, a_winner_of, b_winner_of, a_loser_of, b_loser_of) values (
  'p3', 2, 'pool', 1, '10:25', null,
  'deez-nets', 'aaa-roadside-assistance',
  null, null,
  null, null,
  null, null
) on conflict (id) do update set
  slot = excluded.slot, phase = excluded.phase, court = excluded.court,
  start_time = excluded.start_time, label = excluded.label,
  team_a = excluded.team_a, team_b = excluded.team_b,
  a_seed = excluded.a_seed, b_seed = excluded.b_seed,
  a_winner_of = excluded.a_winner_of, b_winner_of = excluded.b_winner_of,
  a_loser_of = excluded.a_loser_of, b_loser_of = excluded.b_loser_of;
insert into public.games (id, slot, phase, court, start_time, label, team_a, team_b, a_seed, b_seed, a_winner_of, b_winner_of, a_loser_of, b_loser_of) values (
  'p4', 2, 'pool', 2, '10:25', null,
  'annies-friends', 'cinnamon-rolls',
  null, null,
  null, null,
  null, null
) on conflict (id) do update set
  slot = excluded.slot, phase = excluded.phase, court = excluded.court,
  start_time = excluded.start_time, label = excluded.label,
  team_a = excluded.team_a, team_b = excluded.team_b,
  a_seed = excluded.a_seed, b_seed = excluded.b_seed,
  a_winner_of = excluded.a_winner_of, b_winner_of = excluded.b_winner_of,
  a_loser_of = excluded.a_loser_of, b_loser_of = excluded.b_loser_of;
insert into public.games (id, slot, phase, court, start_time, label, team_a, team_b, a_seed, b_seed, a_winner_of, b_winner_of, a_loser_of, b_loser_of) values (
  'p5', 3, 'pool', 1, '10:50', null,
  'deez-nets', 'annies-friends',
  null, null,
  null, null,
  null, null
) on conflict (id) do update set
  slot = excluded.slot, phase = excluded.phase, court = excluded.court,
  start_time = excluded.start_time, label = excluded.label,
  team_a = excluded.team_a, team_b = excluded.team_b,
  a_seed = excluded.a_seed, b_seed = excluded.b_seed,
  a_winner_of = excluded.a_winner_of, b_winner_of = excluded.b_winner_of,
  a_loser_of = excluded.a_loser_of, b_loser_of = excluded.b_loser_of;
insert into public.games (id, slot, phase, court, start_time, label, team_a, team_b, a_seed, b_seed, a_winner_of, b_winner_of, a_loser_of, b_loser_of) values (
  'p6', 3, 'pool', 2, '10:50', null,
  'aaa-roadside-assistance', 'cinnamon-rolls',
  null, null,
  null, null,
  null, null
) on conflict (id) do update set
  slot = excluded.slot, phase = excluded.phase, court = excluded.court,
  start_time = excluded.start_time, label = excluded.label,
  team_a = excluded.team_a, team_b = excluded.team_b,
  a_seed = excluded.a_seed, b_seed = excluded.b_seed,
  a_winner_of = excluded.a_winner_of, b_winner_of = excluded.b_winner_of,
  a_loser_of = excluded.a_loser_of, b_loser_of = excluded.b_loser_of;

-- Bracket rows reference semifinal ids, so they must land after the pool rows.
insert into public.games (id, slot, phase, court, start_time, label, team_a, team_b, a_seed, b_seed, a_winner_of, b_winner_of, a_loser_of, b_loser_of) values (
  'sf1', 4, 'bracket', 1, '11:25', 'Semifinal 1',
  null, null,
  1, 4,
  null, null,
  null, null
) on conflict (id) do update set
  slot = excluded.slot, phase = excluded.phase, court = excluded.court,
  start_time = excluded.start_time, label = excluded.label,
  team_a = excluded.team_a, team_b = excluded.team_b,
  a_seed = excluded.a_seed, b_seed = excluded.b_seed,
  a_winner_of = excluded.a_winner_of, b_winner_of = excluded.b_winner_of,
  a_loser_of = excluded.a_loser_of, b_loser_of = excluded.b_loser_of;
insert into public.games (id, slot, phase, court, start_time, label, team_a, team_b, a_seed, b_seed, a_winner_of, b_winner_of, a_loser_of, b_loser_of) values (
  'sf2', 4, 'bracket', 2, '11:25', 'Semifinal 2',
  null, null,
  2, 3,
  null, null,
  null, null
) on conflict (id) do update set
  slot = excluded.slot, phase = excluded.phase, court = excluded.court,
  start_time = excluded.start_time, label = excluded.label,
  team_a = excluded.team_a, team_b = excluded.team_b,
  a_seed = excluded.a_seed, b_seed = excluded.b_seed,
  a_winner_of = excluded.a_winner_of, b_winner_of = excluded.b_winner_of,
  a_loser_of = excluded.a_loser_of, b_loser_of = excluded.b_loser_of;
insert into public.games (id, slot, phase, court, start_time, label, team_a, team_b, a_seed, b_seed, a_winner_of, b_winner_of, a_loser_of, b_loser_of) values (
  'wf', 5, 'bracket', 1, '12:30', 'Winners'' Final',
  null, null,
  null, null,
  'sf1', 'sf2',
  null, null
) on conflict (id) do update set
  slot = excluded.slot, phase = excluded.phase, court = excluded.court,
  start_time = excluded.start_time, label = excluded.label,
  team_a = excluded.team_a, team_b = excluded.team_b,
  a_seed = excluded.a_seed, b_seed = excluded.b_seed,
  a_winner_of = excluded.a_winner_of, b_winner_of = excluded.b_winner_of,
  a_loser_of = excluded.a_loser_of, b_loser_of = excluded.b_loser_of;
insert into public.games (id, slot, phase, court, start_time, label, team_a, team_b, a_seed, b_seed, a_winner_of, b_winner_of, a_loser_of, b_loser_of) values (
  'le', 5, 'bracket', 2, '12:30', 'Elimination Match',
  null, null,
  null, null,
  null, null,
  'sf1', 'sf2'
) on conflict (id) do update set
  slot = excluded.slot, phase = excluded.phase, court = excluded.court,
  start_time = excluded.start_time, label = excluded.label,
  team_a = excluded.team_a, team_b = excluded.team_b,
  a_seed = excluded.a_seed, b_seed = excluded.b_seed,
  a_winner_of = excluded.a_winner_of, b_winner_of = excluded.b_winner_of,
  a_loser_of = excluded.a_loser_of, b_loser_of = excluded.b_loser_of;
insert into public.games (id, slot, phase, court, start_time, label, team_a, team_b, a_seed, b_seed, a_winner_of, b_winner_of, a_loser_of, b_loser_of) values (
  'lf', 6, 'bracket', 1, '1:35', 'Losers'' Final',
  null, null,
  null, null,
  null, 'le',
  'wf', null
) on conflict (id) do update set
  slot = excluded.slot, phase = excluded.phase, court = excluded.court,
  start_time = excluded.start_time, label = excluded.label,
  team_a = excluded.team_a, team_b = excluded.team_b,
  a_seed = excluded.a_seed, b_seed = excluded.b_seed,
  a_winner_of = excluded.a_winner_of, b_winner_of = excluded.b_winner_of,
  a_loser_of = excluded.a_loser_of, b_loser_of = excluded.b_loser_of;
insert into public.games (id, slot, phase, court, start_time, label, team_a, team_b, a_seed, b_seed, a_winner_of, b_winner_of, a_loser_of, b_loser_of) values (
  'final', 7, 'bracket', 1, '2:40', 'Final',
  null, null,
  null, null,
  'wf', 'lf',
  null, null
) on conflict (id) do update set
  slot = excluded.slot, phase = excluded.phase, court = excluded.court,
  start_time = excluded.start_time, label = excluded.label,
  team_a = excluded.team_a, team_b = excluded.team_b,
  a_seed = excluded.a_seed, b_seed = excluded.b_seed,
  a_winner_of = excluded.a_winner_of, b_winner_of = excluded.b_winner_of,
  a_loser_of = excluded.a_loser_of, b_loser_of = excluded.b_loser_of;
insert into public.games (id, slot, phase, court, start_time, label, team_a, team_b, a_seed, b_seed, a_winner_of, b_winner_of, a_loser_of, b_loser_of) values (
  'decider', 8, 'bracket', 1, '3:45', 'Deciding Game',
  null, null,
  null, null,
  'final', null,
  null, 'final'
) on conflict (id) do update set
  slot = excluded.slot, phase = excluded.phase, court = excluded.court,
  start_time = excluded.start_time, label = excluded.label,
  team_a = excluded.team_a, team_b = excluded.team_b,
  a_seed = excluded.a_seed, b_seed = excluded.b_seed,
  a_winner_of = excluded.a_winner_of, b_winner_of = excluded.b_winner_of,
  a_loser_of = excluded.a_loser_of, b_loser_of = excluded.b_loser_of;

delete from public.teams where id not in ('deez-nets', 'annies-friends', 'aaa-roadside-assistance', 'cinnamon-rolls');

commit;
